balancer/balancer-sdk

balancer-js/package.json, balancer-js/yarn.lock
Builds on #26 
I've moved ethers out of dependencies as we want to use the version from `peerDependencies`.
I've also noticed that we weren't including `@ethersproject/providers` in the package.json file which resulted in us including our own version in the build outputs, doubling the size of the package.
=> Fixup dependencies

.github/workflows/balancer-js.yaml, balancer-js/README.md
This PR cleans up the use of the default working directory and ensures these checks are only run when something in the balancer-js subdirectory changes.
=> CI improvements

.github/workflows/balancer-js.yaml, balancer-js/examples/queryBatchSwap.ts, balancer-js/src/modules/relayer/relayer.module.spec.ts, balancer-js/src/modules/relayer/relayer.module.ts, balancer-js/src/modules/sdk.module.ts, balancer-js/src/modules/swaps/swaps.module.spec.ts, balancer-js/src/modules/swaps/swaps.module.ts, balancer-js/src/sor/sorFactory.spec.ts, balancer-js/src/sor/sorFactory.ts, balancer-js/src/test/lib/mockPool.ts
* Allow all modules to be instantiated directly with config.
* Removed unused network from params for Swaps. Also changed to use SOR provider.
* Moved getNetworkConfig to SorFactory as params are only required there.
* Remove Swaps Network & Provider params. Network wasn't being used and Provider can be taken from SOR. Allows for params to be SOR or config.
* Added fetch/getPools functions to Swaps and Relayer functions as these would be required/useful when used directly.
* Added tests for module instantiation direct/SDK
=> Instantiate all modules with config.

balancer-js/package.json, balancer-js/src/modules/sor/pool-data/onChainData.ts, balancer-js/src/modules/sor/pool-data/subgraphPoolDataService.ts, balancer-js/yarn.lock
Bump SOR package for ERC4626Linear pool types. 
Update Polygon SG to use Linear Pools. 
Update onChain for any Linear pool type.
=> ERC4626 Linear pool support.

balancer-js/README.md
The `ConfigSdk` type no longer exists, changing to the new name in the types file.
=> Fix SDK config type in README

balancer-js/README.md, balancer-js/examples/spotPrice.ts, balancer-js/package.json, balancer-js/src/balancerErrors.ts, balancer-js/src/modules/pools/pool-types/concerns/linear/liquidity.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/linear/spotPrice.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/metaStable/liquidity.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/metaStable/spotPrice.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/spotPrice.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/stablePhantom/liquidity.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/stablePhantom/spotPrice.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/types.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/spotPrice.concern.ts, balancer-js/src/modules/pools/pool-types/linear.module.ts, balancer-js/src/modules/pools/pool-types/metaStable.module.ts, balancer-js/src/modules/pools/pool-types/pool-type.interface.ts, balancer-js/src/modules/pools/pool-types/stable.module.ts, balancer-js/src/modules/pools/pool-types/stablePhantom.module.ts, balancer-js/src/modules/pools/pool-types/weighted.module.ts, balancer-js/src/modules/pools/pools.module.ts, balancer-js/src/modules/pricing/pricing.module.spec.ts, balancer-js/src/modules/pricing/pricing.module.ts, balancer-js/src/modules/sdk.module.ts, balancer-js/src/modules/swaps/queryBatchSwap.ts, balancer-js/src/modules/swaps/swaps.module.ts, balancer-js/src/modules/swaps/types.ts, balancer-js/src/test/lib/constants.ts, balancer-js/src/test/lib/pools_14717479.json, balancer-js/yarn.lock
Add support to make it easy for a user to:
- Get SP for a token pair:
- for a specific pool.
- Get Spot Price (SP) for a token pair:
- considering all paths.
- This is the SP of the most liquid path for pair as found by SOR.
Added snapshot of mainnet pool state in json format to enable testing of path finding.
TO DO 
- SOR package needs updated with some function exposed.
- Update readme.
=> Add pricing module with tests.

balancer-js/package.json, balancer-js/rollup.config.ts, balancer-js/tsconfig.json
TS exclude option can be passed directly in rollup config.
Additionally added rimraf package which deleting all files in dist folder before building.
=> fix: exclude spec files at build

balancer-js/src/lib/constants/network.ts
Frontend is referencing Network.GÖRLI, but SDK was specifying is with a GOERLI spelling. This PR is adding UTF8 spelling as well.
=> fix: add missing goerli with utf8 spelling

balancer-js/src/balancerErrors.ts, balancer-js/src/modules/joins/graph.module.spec.ts, balancer-js/src/modules/joins/graph.ts, balancer-js/src/modules/joins/joins.module.spec.ts, balancer-js/src/modules/joins/joins.module.ts
Adds method to handle non-leaf token joins.
- First we create the calls for leaf tokens
- Then for each non-leaf token we find the action path from the input node to the root by traversing up graph
- We create the calls for this path and add it as a separate chain
=> Generalised joins non leaf input

balancer-js/hardhat.config.js, balancer-js/src/lib/abi/BatchRelayerLibrary.json, balancer-js/src/lib/constants/config.ts, balancer-js/src/modules/joins/joins.module.integration.spec.ts, balancer-js/src/modules/joins/joins.module.ts, balancer-js/src/modules/pools/index.ts, balancer-js/src/modules/relayer/relayer.module.ts, balancer-js/src/test/lib/constants.ts
- ! Runs tests on Goerli fork !
- Run `yarn test:only ./src/modules/joins/joins.module.integration.spec.ts` to see result
- Adds BatchRelayer V4
- Fixes encoding issue in joinPool
- Adds functionality to peek outputRefrences from Relayer
- Creates one set of calls with peek additions.
- static calls and decodes to get peek values (for any node ending in root pool)
- Used to set minAmountOut value for final join amount
- Note - Current RelayerV4 on Goerli is incorrectly handling readonly values. This works for now but will likely need updated when relayer is fixed.
=> Generalised join relayerv4

balancer-js/src/lib/constants/config.ts, balancer-js/src/modules/data/index.ts, balancer-js/src/modules/data/protocol-fees/provider.ts, balancer-js/src/modules/data/types.ts, balancer-js/src/modules/pools/apr/apr.ts, balancer-js/src/types.ts
For MetaStable pools, the protocol applies the SwapFeePercentage to the yield.
For ComposablePools and the WeightedPoolsV2, the protocol's cut is stored in the pool itself accessible via ProtocolFeePercentagesProvider
=> deducting protocol cut on yield tokens

balancer-js/src/modules/subgraph/balancer-v2/Pools.graphql
Adds token > pool > poolType attribute to the SubgraphPoolToken graphql type. These attributes make it trivial to check if a pool is deeply nested, i.e. has pool tokens that are pools themselves.
=> Add attributes to SubgraphPoolToken graphql type

balancer-js/src/modules/data/token-prices/coingecko.spec.ts, balancer-js/src/modules/data/token-prices/index.ts, balancer-js/src/modules/data/token-prices/static.spec.ts, balancer-js/src/modules/data/token-prices/static.ts, balancer-js/src/modules/data/token-prices/types.ts, balancer-js/src/modules/liquidity/liquidity.module.ts, balancer-js/src/modules/pools/apr/apr.spec.ts, balancer-js/src/modules/pools/apr/apr.ts
@gmbronco mentioned the SDK should always be dealing with token addresses in lower case for consistency. In the Balancer API all tokens are fetched and stored with lower case addresses. The tokens on reward gauges are not in lower case and so in the API it wasn't finding prices correctly. 
This fix ensures that reward tokens are fetched correctly, it appears to be working correctly when running the APR examples and when using it with the API. 
Also found another bug where the rewardBreakdown wasn't being scaled by BPT. Added a fix for that too so the breakdown adds up to the total correctly .
=> Use lowercase addresses when finding tokens. Scale rewardTokens correctly.

balancer-js/src/modules/data/token-yields/repository.ts, balancer-js/src/modules/data/token-yields/tokens/rocketpool.spec.ts, balancer-js/src/modules/data/token-yields/tokens/rocketpool.ts
Adding yield information source for rocketpool rETH.
Each yield generating token has an external source for the yield. It can be anything, eg: a contract, subgraph of API. To add a new source:
1. Create a new source in `modules/data/token-yields/tokens/` with an yieldTokens object and a fetcher. Fetchers return APR for each token in basis points.
2. Add a spec to make sure it works ok and returns a correct format: { tokenAddress: apr }
3. import yieldTokens and a fetching function into [yieldSourceMap](https://github.com/balancer-labs/balancer-sdk/blob/develop/balancer-js/src/modules/data/token-yields/repository.ts#L19).
4. Add a new token to `yieldSourceMap` responsible for mapping token addresses to fetching functions.
5. Test it to make sure repository is returning a new APR.
Thats' …
=> adding rocketPool rETH token yield

balancer-js/examples/swapSor.ts, balancer-js/package.json, balancer-js/src/modules/swaps/joinAndExit.integration.spec.ts, balancer-js/src/modules/swaps/joinAndExit.spec.ts, balancer-js/src/modules/swaps/joinAndExit.ts, balancer-js/src/test/lib/mainnetPools.ts, balancer-js/yarn.lock
- Update SOR package to 4.0.1-beta.9. Fixes example where fallback without join/exit is used
- Fixes join/exit paths to work with combination that includes multihop
- Set limits correctly - need to be negative for tokens leaving vault
=> Update to work with multihops and fix limits.

balancer-js/src/types.ts
The frontend currently uses both these types. As part of using the SDK Pool / PoolType / APR's these need to be added here for type compatibility.
=> Add Linear and Managed pool types

balancer-js/src/modules/data/pool/balancer-api.ts, balancer-js/src/modules/data/pool/subgraph.ts
- Make a copy of the args/attrs passed in so they aren't held by reference as this ends up modifying the initial options passed in which can cause confusion.
- Delete the skip arg if a user passes it into the Balancer API as it is not a valid arg.
=> Fix two minor issues with pool data repositories

balancer-js/package.json
minor, but the homepage link on npm is kaputt as linking to folders directly doesn't work on GH. this PR fixes this by linking to the main README. the homepage field is optional, so we can as well remove it since it's the same as the repo url
if we want to have a deep link, afaik the only alternative is a blob https://github.com/balancer-labs/balancer-sdk/blob/master/balancer-js/README.md
up to you!
=> correct npm homepage url

balancer-js/src/modules/data/index.ts, balancer-js/src/modules/data/token-prices/subgraph.spec.ts, balancer-js/src/modules/data/token-prices/subgraph.ts
Issue reported by Markus: `customSubgraphUrl` is being ignored on some frontend requests.
Fix: update SubgraphPriceRepository to use customSubgraphUrl provided by SDK config.
At first, this is not an urgent issue, so feel free to review/approve after the holiday break.
=> Fix SubgraphPriceRepository overriding customSubgraphUrl provided on SDK config

balancer-js/README.md, balancer-js/examples/exitExactBPTIn.ts, balancer-js/examples/exitExactTokensOut.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/linear/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/metaStable/exit.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/metaStable/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/exit.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/stablePhantom/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/types.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/exit.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/exit.concern.ts, balancer-js/src/types.ts
See [Asana](https://app.asana.com/0/1201380039585484/1203677866180075/f)
- Add `expectedAmountsOut` to `exitExactBPTIn` output on exit concerns
- Add `expectedBPTIn` to `exitExactTokensOut` output on exit concerns
- Remove `maxBPTIn` from `exitExactBPTIn` output on exit concerns since they simply replicate user input `bptIn`
- Remove `minAmountOut` from `exitExactTokensOut` output on exit concerns since they simply replicate user input `amountsOut`
- Update examples and readme to reflect changes
=> Add expected amounts out to exit pool methods

balancer-js/package.json
I was running into some weird issues running the hardhat fork because my .env file looked like this:
```
ALCHEMY_URL=https://eth-mainnet.alchemyapi.io/v2/...
```
Took a while to discover this grep was picking up the polygon url despite it being commented out because it was the last ALCHEMY_URL in the file. 
Sourcing this file then echoing the value should be more reliable. This works on Ubuntu 22.04, please test it works on OSX before merging.
=> Fetch ALCHEMY_URL in a more reliable way

balancer-js/package.json, balancer-js/yarn.lock
Frontend breaks with latest ethersproject/base64 since it still on node 14 which doesn't support atob natively. Fixing the version to 5.5.0 to be updated once frontend upgrades to node16.
=> 👨‍🔧fixing ethersproject/base64 version for node14 frontend

balancer-js/src/modules/data/token-prices/coingecko-historical.ts, balancer-js/src/modules/data/token-prices/coingecko.ts, balancer-js/src/modules/sor/token-price/coingeckoTokenPriceService.ts
CoinGecko price services need to resolve chainId to coingecko platformId and tokenId.
Added Gnosis-chain values.
=> feat: added Gnosis-chain platformId to Coingecko service

balancer-js/.eslintrc.js, balancer-js/src/lib/utils/slippageHelper.spec.ts, balancer-js/src/modules/data/token-yields/tokens/tranchess.spec.ts, balancer-js/src/modules/data/token-yields/tokens/tranchess.ts, balancer-js/src/modules/swaps/swaps.module.integration.spec.ts
Current build breaks because of direct 'ethers*' imports
Probably related to rollup config not being able to resolve the 'ethers*'
Migrate to: imports (globals: { ethers: 'ethers' }) once we switch to ethers vs individual packages
=> 👨‍🔧build issues with direct ethers/lib import

balancer-js/examples/swapSor.ts, balancer-js/package.json, balancer-js/src/lib/constants/config.ts, balancer-js/src/modules/sor/sor.module.ts, balancer-js/src/test/lib/constants.ts, balancer-js/src/types.ts, balancer-js/yarn.lock
- Update SOR package to [4.1.0-beta.0](https://github.com/balancer-labs/balancer-sor/releases/tag/4.1.0-beta.0).
-  Adds configurable connecting tokens for Boosted Paths where pools containing tokenIn/Out and connectingTokens will be used in Boosted Path creation.
- Add `sorConnectingTokens` with some initial token details.
=> Update to SOR 4.1.0-beta.0. Add config for SOR connecting tokens.

balancer-js/src/modules/data/token-prices/coingecko.ts
We assume native asset is ETH unless network is Polygon. But this should also check for network Gnosis as native token is xDai.
=> feat: missing native in token gecko fetch

balancer-js/src/lib/utils/time.ts, balancer-js/src/modules/pools/fees/fees.ts, balancer-js/src/modules/pools/volume/volume.ts
There are some pools with very high volume, but zero liquidity, e.g.
https://app.balancer.fi/#/ethereum/pool/0xa30ac4a3bf3f680a29eb02238280c75acbb89d6d0002000000000000000000d3
https://app.balancer.fi/#/ethereum/pool/0x4eebc19e5f29dec3dea07f66b9e707afc8f28c060002000000000000000000b3
It happens because the volume corresponds to the total volume, not the past 24h. This pr should fix this + the same problem with fees
=> Fix bug with volume snapshot and fees calculation

balancer-js/src/modules/pools/pool-types/concerns/composableStable/join.concern.ts
Fix a build warning introduced when adding expectedBptOut to join concerns outputs
=> Minor expectedBptOut hotfix

balancer-js/src/modules/data/pool/balancer-api.ts
Bug: @Matthews3301 Discovered a bug with the API data repository when testing gnosis-chain in https://github.com/balancer-labs/frontend-v2/pull/2637. Gnosis chain only has 4 pools and when re-loading the pools the same 4 were continually duplicated so there were 8 results, then 12 etc. 
This happened because AppSync returns `nextToken` as `null` when you've returned all possible results. We weren't handling this and instead we were continually running the same query over and over and appending the returned pools to the cache. 
Fix: When nextToken is null, don't query the API any more, instead fetch pools only from the local cache. This does mean the Pools are not refreshed from the API but this happens for all pools currently anyway because of this local cache.
=> Fix bug when API Pools Data Repository reaches end of pools

balancer-js/src/lib/utils/index.ts, balancer-js/src/modules/graph/graph.ts, balancer-js/src/modules/pools/pool-type-concerns.ts, balancer-js/src/modules/pools/queries/get_encoder.ts, balancer-js/src/types.ts
Updates to check for "Linearish" pools. When a new Linear pool type is added it only needs to be added to `PoolType`.
Also fixes exitAction which was incorrectly adding to joinAction.
=> Change to handle new Linear pools easily.

balancer-js/src/lib/constants/config.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/exit.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/exit.concern.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/exit.concern.ts
Stable Exit Refactored with comments;
- Refactoring exit functions with exactBPTIn and exactTokensOut;
- Refactoring integration and unit tests, using TestPoolHelper instead of pools JSON, using old block number to avoid fee discount from amounts;
- Fixing amounts downscaling problems;
=> Stable exit refactor

balancer-js/package.json, balancer-js/src/modules/pools/pool-type-concerns.ts, balancer-js/src/modules/sor/pool-data/onChainData.ts, balancer-js/src/types.ts, balancer-js/yarn.lock
* Add new Linear pools to `PoolType`
EulerLinear
BeefyLinear
GearboxLinear
MidasLinear
ReaperLinear
SiloLinear
TetuLinear
YearnLinear
* Use `PoolType` instead of SOR filter to allow new pools to be added without SOR package updates
* Remove HighAmpComposableStable as its not an official Balancer Pool
=> Add new Linear pool types.

balancer-js/src/modules/exits/exits.module.ts, balancer-js/src/modules/joins/joins.module.integration.spec.ts, balancer-js/src/modules/joins/joins.module.ts, balancer-js/src/modules/relayer/relayer.module.ts, balancer-js/src/modules/vaultModel/poolModel/poolModel.ts, balancer-js/src/modules/vaultModel/poolModel/swap.ts, balancer-js/src/modules/vaultModel/vaultModel.module.ts
See #322 for context.
Next step taken to reduce gas cost:
- swap/batchSwap → use swap rather than batchSwap whenever performing a batchSwap with a single hop
=> Reduce Generalised Join/Exit Gas Cost (part 2) - WIP

balancer-js/src/modules/data/token-prices/coingecko-historical.ts, balancer-js/src/modules/data/token-prices/coingecko.spec.ts, balancer-js/src/modules/data/token-prices/coingecko.ts
We are getting a lot of Coingecko network errors in Sentry. Probably due to uncaught axios errors. This is an attempt to fix this.
=> fix: handle coingecko request errors

balancer-js/examples/exitGeneralised.ts, balancer-js/src/lib/utils/index.ts, balancer-js/src/modules/exits/exits.module.integration-mainnet.spec.ts, balancer-js/src/modules/exits/exits.module.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exitV2.concern.integration.spec.ts, balancer-js/src/modules/vaultModel/poolModel/exit.ts, balancer-js/src/modules/vaultModel/poolSource.ts, balancer-js/src/test/lib/constants.ts
- Fix token sorting error within vault model
- I believe this was caused by the recent changes to token order on the subgraph and SDK
- Tests are passing, but I'm not confident that removing the token sorting present on the vault model won't cause any knock-on effects. @johngrantuk let me know what you think.
- Fix vault model incorrectly updating pool state during exits
- Pool state being wrong don't currently cause any issues because exits don't perform consecutive operations on the same pool. It's nice to have this fixed anyway. It should follow a [fix on the SOR ](https://github.com/balancer-labs/balancer-sor/pull/368/files)
- Refactor exitGeneralised to run test on mainnet and use updated helpers
- Fix test failing due to blockNumber being too old
=> Fix token sorting error

balancer-js/src/modules/pools/apr/apr.integration.spec.ts
When external data token yield sources are down tests are failing. We might be better off with unit tests only.
=> skipping APR integration tests

balancer-js/README.md, balancer-js/src/modules/pools/index.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exit.concern.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/linear/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/metaStable/exit.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/metaStable/exit.concern.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/exit.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/exit.concern.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/stablePhantom/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/types.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/exit.concern.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/exitV1.concern.integration.spec.ts, balancer-js/src/types.ts
Per Gareth's request `singleTokenMaxOut` was renamed to `singleTokenOut` in order to make it more understandable.
=> Rename singleTokenMaxOut parameter to singleTokenOut

balancer-js/examples/data/token-prices.ts, balancer-js/src/lib/utils/debouncer.spec.ts, balancer-js/src/lib/utils/debouncer.ts
Coingecko has a limit of 180 tokens per one request. I added a limit param to the debouncer to make a separate coingecko call  when the limit is reached.
=> fix: coingecko 414

balancer-js/src/lib/utils/math.ts
Add some comments explaining what the custom `parseFixed` / `formatFixed` functions do. I'm not sure if `formatFixed` is actually useful or if it got added by accident during the large merges @gmbronco and I added in #98.
=> Add math comments

balancer-js/src/modules/data/index.ts, balancer-js/src/modules/data/token-prices/provider.ts, balancer-js/src/modules/pools/apr/apr.ts
When token price was missing APRs were throwing. Changed it to soft fail with a log message.
=> fix: handle missing token price in APRs

balancer-js/src/lib/constants/config.ts, balancer-js/src/lib/constants/network.ts
Added the network config for the fantom network
- Using the BEETS address for BAL.
- No gauges on fantom, so `gaugeClaimHelper` uses the zero address and `gaugesSubgraph` is empty, let me know if this is ok.
=> Added fantom network config

balancer-js/src/modules/data/pool/subgraph-helpers.ts, balancer-js/src/modules/data/pool/subgraph.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exit.concern.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exitV1.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exitV2.concern.integration.spec.ts, balancer-js/src/test/fixtures/pools-mainnet.json, balancer-js/src/test/fixtures/pools-polygon.json, balancer-js/src/test/lib/exitHelper.ts, balancer-js/src/test/lib/pools-json-repository.ts, balancer-js/src/test/lib/utils.ts
Our tests were failing due to fetching outdated pool data from Subgraph. As Subgraph is regularly pruned and only stores blocks from the last 24 hours, any tests requiring older data should be updated with static JSONs or fetched from an archive state.
This PR refactors the failing tests by replacing the `TestPoolHelper` method, which previously retrieved pool state at a specific blockNumber from the subgraph and the RPC. Instead, we now use a static JSON file instead of subgraph and use a provider to fetch the pool from a specific block, ensuring that the data is synced to the desired blockNumber.
`testPoolHelper` is replaced with two new methods: `getPoolFromFile` and `updateFromChain`
* `getPoolFromFile` - returns a fixed pool from a JSON file, ensuring the tests are repeatable
* …
=> specs: json pools

balancer-js/src/modules/data/token-yields/repository.spec.ts, balancer-js/src/modules/data/token-yields/repository.ts
Making sure we fetch the data just once instead of calling the URL whenever .find method is used.
=> fix: yield tokens repository

balancer-js/examples/swapSor.ts, balancer-js/package.json, balancer-js/src/lib/abi/gyroEV2.json, balancer-js/src/modules/sor/pool-data/onChainData.ts, balancer-js/src/test/lib/constants.ts, balancer-js/src/types.ts, balancer-js/yarn.lock
- Update SOR to 4.1.1-beta.9 (Adds GyroE V2 support)
- Update onchain call to get token rates for GyroE V2 pools
=> GyroE V2 Support

balancer-js/examples/exitGeneralised.ts, balancer-js/src/modules/exits/exits.module.integration-mainnet.spec.ts, balancer-js/src/modules/exits/exits.module.integration.spec.ts, balancer-js/src/modules/exits/exits.module.ts, balancer-js/src/modules/exits/exitsProportional.module.integration.spec.ts, balancer-js/src/modules/pools/index.ts
There was an issue with the current flow and unwrapping:
1. With vault model:
- Initially tries with no unwrap, gets `expectedAmountsOutByExitPath` by using TS maths
- `expectedAmountsOutByExitPath` is compared to linear main balances and if less unwrap is found
- Because we use TS maths no errors are thrown and unwrap is discovered
2. With static model:
- Initially tries with no unwrap, gets `expectedAmountsOutByExitPath` by using static call
- The static call throws because its not possible to do this exit
- We can't do rest
This would cause issues on UI.
Here I change it to a new flow.
- `getExitInfo`: 
- Returns the info UI needs to display to user (based off TS maths) and whether an unwrap is needed
- returns estimatedOutputs and needsUnwrap
- No concept of slippage here
- No calls …
=> Updated flow and test.

balancer-js/src/lib/constants/config.ts, balancer-js/src/lib/constants/network.ts, balancer-js/src/test/lib/constants.ts
Missing multicall, because the multicall address of makerDAO is not yet on master:
Link of makerDAO multicall PR: https://github.com/makerdao/multicall/pull/48
=> Adding Sepolia Network

balancer-js/examples/exitGeneralised.ts, balancer-js/src/modules/exits/exits.module.integration-mainnet.spec.ts, balancer-js/src/modules/exits/exits.module.integration.spec.ts, balancer-js/src/modules/exits/exits.module.ts, balancer-js/src/modules/exits/exitsProportional.module.integration.spec.ts, balancer-js/src/modules/exits/testHelper.ts, balancer-js/src/modules/graph/graph.module.spec.ts, balancer-js/src/modules/graph/graph.ts, balancer-js/src/modules/joins/joins.module.ts, balancer-js/src/modules/pools/index.ts
With the previous solution, generalisedExit was able to only exit with the following options:
1. exit directly to all underlying main tokens
2. exit by unwrapping all underlying wrapped tokens
This PR updates option 2 to:
2. exit by unwrapping only selected underlying wrapped tokens
See [this asana task](https://app.asana.com/0/1201380039585484/1204564187636490/f) for more details on which problem this solves.
=> Generalised Exit - Add ability to exit by selectively unwrapping tokens

balancer-js/src/modules/exits/testHelper.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exitV2.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exitV3.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exitV4.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/join.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/join.concern.ts, balancer-js/src/test/fixtures/pools-mainnet.json, balancer-js/src/test/lib/mainnetPools.ts, balancer-js/src/test/lib/utils.ts
Also took the opportunity to:
- Refactor exit Composable Stable V3 integration tests to reuse existing test helpers
- Extracted some helper constants to test utils so they can be reused
=> Add support to join/exit ComposableStable V4 Pools

balancer-js/src/lib/constants/config.ts, balancer-js/src/modules/sor/token-price/coingeckoTokenPriceService.ts, balancer-js/src/types.ts
Moving Coingecko `platformId` and `nativeAssetId` to the config files instead of being inside coingecko, so that these settings aren't missed when adding a new network. Also added settings for zkevm.
=> Move coingecko settings from token prices file to config

balancer-js/examples/pools/liquidity.ts, balancer-js/src/modules/liquidity/liquidity.module.ts, balancer-js/src/modules/pools/index.ts
See [this Asana task](https://app.asana.com/0/1201380039585484/1204551609513252/f) for more info.
The initial suggestion was to add `bptPrice` as an extra field to liquidity, but that would add a breaking change, so I added a separate external method that uses liquidity service to calculate the bptPrice in USD.
Let me know if you think this approach makes sense or if you'd rather update liquidity service to return both `liquidity` and `bptPrice` at the same time.
=> Add bptPrice calculation to liquidity service

balancer-js/src/lib/constants/config.ts, balancer-js/src/modules/data/index.ts, balancer-js/src/types.ts
We don't have a blocks subgraph for Gnosis Chain or zkEVM, instead set the average block time and fetch based on that for chains without a blocks subgraph set.
Tested with the API and it is correctly calculating volumes for zkEVM, Gnosis and Mainnet
=> Use average block time for chains without blocks subgraph

balancer-js/examples/data/pools.ts, balancer-js/examples/pools/join/join-with-eth.ts, balancer-js/src/modules/data/pool/subgraphOnChain.ts, balancer-js/src/modules/data/types.ts, balancer-js/src/modules/pools/index.ts, balancer-js/src/test/factories/data.ts, balancer-js/src/types.ts
* Exposing join and exit functions on the pools module instead of the pool model (which is wrapped). This way, the pool state can be passed directly. Since the frontend already fetches and stores pools as variables, I believe there is no need for the "Wrapped" version. We can consider refactoring it out later. https://github.com/balancer/balancer-sdk/pull/458/files#diff-f4169f56974e94f924689e0ff5c152879afa7eae66ef87c442a87096302a09b0R461
* The SubgraphOnChain repository now has the capability to refresh just one pool instead of refreshing all of them. Faster for join and exit cases. https://github.com/balancer/balancer-sdk/pull/458/files#diff-e531f833d92ed2706fec5a309890f010dc43c1b6438ef9d6a7f59be454e03ab4R123
=> Refresh pool data

balancer-js/src/lib/utils/tenderlyHelper.ts, balancer-js/src/modules/exits/testHelper.ts, balancer-js/src/modules/joins/joins.module.integration.spec.ts, balancer-js/src/modules/simulation/simulation.module.ts, balancer-js/src/types.ts
This PR removes Tenderly default config and requires custom config to be provided when using Tenderly simulations on generalisedJoin/Exit.
=> Remove tenderly default config

balancer-js/src/lib/constants/addresses.json
After the Multichain bridge hack we've switched to a new BAL token on Avalanche using LayerZero instead
=> Update BAL Address on Avalanche

balancer-js/src/lib/constants/config.ts
- Switched to v3 multicall
- Switched to new latest subgraph endpoint instead of the fixed version.
=> Update Sepolia subgraph and multicall

balancer-js/package.json, balancer-js/src/modules/sor/pool-data/multicall/fx.ts, balancer-js/src/modules/sor/pool-data/multicall/gyroEv2.ts, balancer-js/src/modules/sor/pool-data/onChainData.ts, balancer-js/yarn.lock
* Update SOR package
* Update onchainData for FX pools
=> Sor update 4.1.1 beta.12

balancer-js/src/lib/constants/config.ts
- Add a quick temporary fix by ignoring a Gyro pool that is preventing swaps from working properly on mainnet
Note: we should later figure out why this pool is resulting in an error and fix it
=> Ignore gyro pool that is causing swap preview to fail

balancer-js/examples/pools/volume/volume.avalanche.ts, balancer-js/src/lib/constants/config.ts
Fixes volume on Avalanche and adds example to ensure it works correctly.
=> Add example for retrieving volume on Avalanche

balancer-js/src/lib/constants/config.ts, balancer-js/src/modules/data/gauge-controller/multicall.spec.ts, balancer-js/src/modules/data/gauge-controller/multicall.ts, balancer-js/src/modules/data/index.ts, balancer-js/src/modules/data/liquidity-gauges/provider.ts
Still using the normal gaugeController for testnets;
=> Using gaugeControllerCheckpointer for mainnet network;

balancer-js/src/lib/utils/logger.ts, balancer-js/src/modules/data/pool/subgraph.ts, balancer-js/src/modules/data/pool/subgraphOnChain.ts, balancer-js/src/modules/exits/exits.module.integration-mainnet.spec.ts, balancer-js/src/modules/exits/exits.module.integration.spec.ts, balancer-js/src/modules/exits/exits.module.ts, balancer-js/src/modules/graph/graph.ts, balancer-js/src/modules/sor/pool-data/subgraphPoolDataService.ts, balancer-js/src/test/lib/constants.ts
In generalisedExits we weren't correctly handling phantomStables. These have no exit function and must be exited using a batchSwap.
* Added integration test against bbausd V1
* Added createBatchSwap function that handles case where a swap action has more than one child
=> Generalised exit phantom

balancer-js/src/modules/data/pool/balancer-api.ts
We had some issues with the Balancer API when filtering pools by token/type, and the root cause of this is that we had a skip variable that we were sometimes using to skip from the API fetch and sometimes to skip from the cache, and this was causing strange things to happen when they were in conflict. 
This PR refactors the Balancer API pool fetcher to always pull all pools, save them to the cache, and return from the cache as soon as enough are available or the query finishes.
=> Refactor Balancer API fetcher to pull all pools and always use the cache

balancer-js/examples/pools/bpt-price.ts, balancer-js/src/modules/data/token-prices/coingecko-historical.ts, balancer-js/src/modules/data/token-prices/coingecko.ts, balancer-js/src/modules/pools/impermanentLoss/impermanentLoss.integration.spec.ts
Adding example for bptPrice;
Separating coingecko token prices requests by chunks of 10, coingecko is only allowing 10 tokens per request in the free plan, they have a paid plan for more token prices (https://www.coingecko.com/en/api/pricing);
=> BPT Price Fetch Error - Separating in chunk of 10, coingecko only allows 10 token prices per request now;

balancer-js/examples/swaps/swapDebug.ts, balancer-js/src/modules/sor/pool-data/subgraphPoolDataService.ts, balancer-js/src/test/lib/utils.ts
A few conditions lead to SDK failing to route a valid swap:
- poolsToIgnore file lists pools from all chains
- poolsToIgnore filter was comparing pool addresses by truncating pool ids
Problem:
- 2 different pools had different ids, but the same address (on different chains)
Fix:
- update poolsToIgnore filter to compare pool ids instead of addresses
Extra:
- add a swapDebug example to facilitate swap debugging within the SDK
=> Fix pools to ignore filter

balancer-js/src/lib/constants/config.ts
Closes #580 
Main changes:
- Update `subgraph` and `gaugesSubgraph` config url for all chains
Questions:
- do we still need to support `blockNumbersSubgraph`? -> used to calculate accumulated swapFees on the last 24h
- do we need to push those changes to the master branch and perform a `latest` release?
- I didn't add subgraph info for `Mode` because we don't have any config info for it - do we need to add it?
- I didn't update subgraph info for `Goerli` because we don't have a new one - should we remove all config info for Goerli and drop support for it?
=> Update subgraph urls (moving away from hosted service)
