balancer-js/src/modules/subgraph/README.md, balancer-js/src/modules/subgraph/codegen.yml, balancer-js/src/modules/subgraph/generated/balancer-subgraph-schema.graphql, balancer-js/src/modules/subgraph/generated/balancer-subgraph-types.ts
Hi  there. I found some typos.
- run `yarn subgraph:generate` 
- fix kind of typo in README
- fix codegen.yml 
Could you review ? @garethfuller
=> Fix codegen.yml

balancer-js/package.json, balancer-js/yarn.lock
Bump SOR version. Generic boostedPaths and updated weighted pool precision.
=> John/sor 4.0.0 beta.3

balancer-js/docker-compose.yml
Adding a docker-compose config for running frontend with local version of the SDK.
=> docker-compose for running frontend with local SDK code

balancer-js/package.json, balancer-js/src/lib/constants/config.ts, balancer-js/src/modules/sor/sor.module.ts, balancer-js/src/types.ts, balancer-js/yarn.lock
* This version of the SOR uses a new general graph algorithm to create the paths through boosted pools
=> Bump SOR to 4.0.1-beta.0. Removed unused pool config.

balancer-js/examples/pools/calculateLiquidity.ts, balancer-js/src/lib/utils/math.spec.ts, balancer-js/src/lib/utils/math.ts, balancer-js/src/modules/data-providers/token-price/static.provider.ts, balancer-js/src/modules/liquidity/liquidity.module.spec.ts, balancer-js/src/modules/liquidity/liquidity.module.ts, balancer-js/src/modules/pools/pool-types/concerns/linear/liquidity.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/metaStable/liquidity.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/liquidity.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/liquidity.concern.ts, balancer-js/src/test/fixtures/liquidityPools.json, balancer-js/yarn.lock
Adds a `parseFixed` wrapper function that automatically trims additional decimals so that underflow errors don't occur if a user passes in any values with too many decimal places. 
Adds tests for this new function and a test pools liquidity calculation test case for it.
=> Fix underflow errors

balancer-js/src/modules/swaps/swap_builder/batch_swap_builder.spec.ts, balancer-js/src/modules/swaps/swap_builder/batch_swap_builder.ts, balancer-js/src/modules/swaps/swap_builder/single_swap_builder.ts, balancer-js/src/modules/swaps/swap_builder/swap_info_decorator.spec.ts, balancer-js/src/modules/swaps/swap_builder/swap_info_decorator.ts, balancer-js/src/modules/swaps/swaps.module.integration.spec.ts, balancer-js/src/modules/swaps/swaps.module.spec.ts, balancer-js/src/modules/swaps/swaps.module.ts, balancer-js/src/modules/swaps/types.ts, balancer-js/yarn.lock
Adding custom recipient address to swaps.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202509309531723
=> fix custom swap recipient

balancer-js/examples/swapLocalFork.ts, balancer-js/examples/swapQuery.ts, balancer-js/package.json, balancer-js/src/modules/sor/pool-data/onChainData.ts, balancer-js/src/modules/subgraph/generated/balancer-subgraph-schema.graphql, balancer-js/src/modules/subgraph/generated/balancer-subgraph-types.ts, balancer-js/src/modules/subgraph/graphql/Pools.graphql, balancer-js/yarn.lock
- Update SOR package to 4.0.1-beta.3 which has support for ComposableStable.
- Updates Subgraph/Onchain to add Gyro pools and ComposableStable. 
- Added SwapQuery example.
=> SOR-4.0.1-beta.3 - ComposableStable

balancer-js/package.json, balancer-js/src/modules/pools/pool-types/concerns/metaStable/join.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/join.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/exit.concern.ts, balancer-js/yarn.lock
updated version number of dependency:
"@balancer-labs/sor": "^4.0.1-beta.3"
=> use always SOR instead of georgeroman-sdk

balancer-js/README.md
enhanced README for how to run the provided SDK js examples
=> updated README to include instructions on how to run js examples

balancer-js/src/modules/joins/graph.module.spec.ts, balancer-js/src/modules/joins/graph.ts, balancer-js/src/modules/joins/joins.module.integration.spec.ts, balancer-js/src/modules/joins/joins.module.spec.ts, balancer-js/src/modules/joins/joins.module.ts, balancer-js/src/modules/pools/provider.ts, balancer-js/src/types.ts
Adds optional to determine if we use wrapping for main tokens
=> Generalised joins without wrap

balancer-js/examples/pools/aprs.polygon.ts, balancer-js/src/lib/constants/config.ts, balancer-js/src/modules/data/index.ts, balancer-js/src/modules/data/liquidity-gauges/multicall.spec.ts, balancer-js/src/modules/data/liquidity-gauges/multicall.ts, balancer-js/src/modules/data/liquidity-gauges/provider.ts, balancer-js/src/modules/data/liquidity-gauges/subgraph.ts, balancer-js/src/modules/data/pool/subgraph.ts, balancer-js/src/modules/pools/apr/apr.ts, balancer-js/src/modules/subgraph/balancer-gauges/LiquidityGauges.graphql, balancer-js/src/modules/subgraph/generated/balancer-gauges.graphql, balancer-js/src/modules/subgraph/generated/balancer-gauges.ts, balancer-js/src/modules/subgraph/generated/balancer-subgraph-schema.graphql, balancer-js/src/modules/subgraph/generated/balancer-subgraph-types.ts, balancer-js/src/test/factories/sdk.ts, balancer-js/src/types.ts
For veBal pool protocolApr should be added only when you stake the tokens and that's represented by the max value.
=> fix: minimal APR shouldn't include protocol APR & L2 support

balancer-js/package.json, balancer-js/src/lib/abi/ComposableStable.json, balancer-js/src/modules/sor/pool-data/onChainData.ts
Use actualSupply for ComposableStable instead of totalSupply due to protocol fees.
=> Version 0.1.23

balancer-js/src/modules/pools/index.ts, balancer-js/src/modules/pools/pool-type-concerns.ts, balancer-js/src/modules/pools/pool-types/composableStable.module.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exit.concern.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/types.ts, balancer-js/src/pool-composable-stable/encoder.ts, balancer-js/src/pool-composable-stable/index.ts, balancer-js/src/types.ts
Adding composable stable pools support.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202957048330326
=> feat: composable stable pools

balancer-js/README.md, balancer-js/examples/joinGeneralised.ts, balancer-js/src/lib/constants/config.ts, balancer-js/src/modules/joins/joins.module.integration.spec.ts, balancer-js/src/modules/joins/joins.module.ts, balancer-js/src/modules/pools/index.ts, balancer-js/src/modules/relayer/relayer.module.ts, balancer-js/src/test/lib/constants.ts
- Uses slippage setting to set minAmounts
- Update to working RelayerV4.
- Add example
- Add some documentation
=> Generalised joins slippage

balancer-js/src/modules/joins/graph.ts, balancer-js/src/modules/joins/joins.module.integration.spec.ts, balancer-js/src/modules/joins/joins.module.ts, balancer-js/src/test/lib/constants.ts
- Add Integration tests for boostedMeta and boostedMetaBig pools
=> Generalised Joins - BoostedMeta and BoostedMetaBig Integration Tests

balancer-js/src/modules/data/pool/subgraph.ts, balancer-js/src/modules/joins/graph.module.spec.ts, balancer-js/src/modules/joins/graph.ts, balancer-js/src/modules/joins/joins.module.ts, balancer-js/src/test/factories/pools.ts, balancer-js/src/types.ts
Adds price impact calculation for joins.
=> Price Impact

balancer-js/src/modules/joins/joins.module.integration.spec.ts, balancer-js/src/test/lib/constants.ts
- Refactored tests
- Added tests for joining with nested boosted BPTs
=> Generalised joins testing

balancer-js/examples/pools/calculateLiquidity.ts, balancer-js/examples/pools/liquidity.ts, balancer-js/src/modules/data/index.ts, balancer-js/src/modules/data/token-prices/aave-rates.ts, balancer-js/src/modules/data/token-prices/index.ts, balancer-js/src/modules/data/token-prices/provider.ts
Token prices for wrapped Aave tokens were off because of missing aToken rate.
=> fix: wrapped aave tokens rate

balancer-js/src/modules/joins/graph.ts, balancer-js/src/modules/joins/joins.module.integration.spec.ts, balancer-js/src/modules/joins/joins.module.ts
Refactor generalisedJoin to use joinPaths similar to exitPaths on generalisedExit
=> Generalised joins refactor

balancer-js/examples/swapSor.ts, balancer-js/package.json, balancer-js/src/modules/swaps/joinAndExit.integration.spec.ts, balancer-js/src/modules/swaps/joinAndExit.spec.ts, balancer-js/src/modules/swaps/joinAndExit.ts, balancer-js/src/test/lib/mainnetPools.ts, balancer-js/yarn.lock
- Update SOR package to 4.0.1-beta.9. Fixes example where fallback without join/exit is used.
- Fixes join/exit paths to work with combination that includes multihop
- Set limits correctly - need to be negative for tokens leaving vault
=> Release v0.1.32

balancer-js/examples/pools/aprs.arbitrum.ts, balancer-js/src/lib/constants/config.ts, balancer-js/src/modules/data/liquidity-gauges/multicall.ts, balancer-js/src/modules/data/liquidity-gauges/provider.ts, balancer-js/src/modules/pools/apr/apr.integration.spec.ts, balancer-js/src/modules/pools/apr/apr.ts, balancer-js/src/modules/pools/pool-type-concerns.ts, balancer-js/src/modules/subgraph/balancer-gauges/LiquidityGauges.graphql, balancer-js/src/modules/subgraph/generated/balancer-gauges.ts, balancer-js/src/modules/subgraph/generated/balancer-subgraph-schema.graphql, balancer-js/src/modules/subgraph/generated/balancer-subgraph-types.ts, balancer-js/src/types.ts
Adds staking APRs on L2 based on new gauges subgraph data.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203201632204059
- https://app.asana.com/0/0/1203311103746523
=> L2 staking APRs

balancer-js/package.json, balancer-js/src/test/lib/constants.ts, balancer-js/yarn.lock
- Update SOR to 4.0.1-beta.10 (limits Polygon Boosted path lengths)
=> SOR 4.0.1 beta.10

balancer-js/src/balancerErrors.ts, balancer-js/src/modules/exits/exits.module.integration.spec.ts, balancer-js/src/modules/exits/exits.module.ts, balancer-js/src/modules/joins/joins.module.integration.spec.ts, balancer-js/src/modules/joins/joins.module.ts, balancer-js/src/modules/relayer/relayer.module.ts
As discussed adds a final check for token deltas based off call data.
=> Add assertion of call deltas

balancer-js/package.json, balancer-js/src/modules/data/pool/subgraph.ts, balancer-js/src/modules/sor/pool-data/subgraphPoolDataService.ts, balancer-js/yarn.lock
- Update SOR to [4.0.1-beta.11](https://github.com/balancer-labs/balancer-sor/releases/tag/4.0.1-beta.11)
- Change to filter SG - totalShares_gt: '0.000000000001'
=> Bump SOR to 4.0.1-beta.11. Filter sg update.

balancer-js/package.json, balancer-js/yarn.lock
Update [SOR package](https://github.com/balancer-labs/balancer-sor/releases/tag/4.0.1-beta.12)
=> John/sor 4.0.1 beta.12

balancer-js/package.json
Update [SOR package](https://github.com/balancer-labs/balancer-sor/releases/tag/4.0.1-beta.12)
=> Release v0.1.37

balancer-js/package.json
Since `develop` does not allow us to push changes, I created the PR just to bump the version and have everyone able to keep track of the latest versions we're releasing.
=> Version Bump

balancer-js/examples/data/token-prices.ts, balancer-js/src/lib/utils/debouncer.spec.ts, balancer-js/src/lib/utils/debouncer.ts, balancer-js/src/lib/utils/index.ts, balancer-js/src/lib/utils/tokens.ts, balancer-js/src/modules/data/index.ts, balancer-js/src/modules/data/token-prices/aave-rates.ts, balancer-js/src/modules/data/token-prices/coingecko-historical.ts, balancer-js/src/modules/data/token-prices/coingecko.ts, balancer-js/src/modules/data/token-prices/historical-price-provider.ts, balancer-js/src/modules/data/token-prices/index.ts, balancer-js/src/modules/data/token-prices/provider.ts, balancer-js/src/modules/data/token-prices/subgraph.spec.ts, balancer-js/src/modules/data/token-prices/subgraph.ts, balancer-js/src/modules/pools/impermanentLoss/impermanentLoss.spec.ts, balancer-js/src/modules/pools/impermanentLoss/impermanentLossService.ts, balancer-js/src/test/factories/data.ts, balancer-js/src/test/lib/ImpermanentLossData.ts
* extracted debouncer from refactored coingecko price repository
* added subgraph price repository
* setup a fallback to subgraph when coingecko is missing a price
=> Subgraph token prices

.github/workflows/beta-release.yaml
Automate beta releases on develop branch.
=> new: beta release workflow

.github/workflows/beta-release.yaml, balancer-js/examples/data/token-yields.ts, balancer-js/package.json, balancer-js/src/modules/data/token-yields/repository.ts, balancer-js/src/modules/data/token-yields/tokens/sfrxeth.spec.ts, balancer-js/src/modules/data/token-yields/tokens/sfrxeth.ts, balancer-js/src/modules/exits/exits.module.ts
- sfrxETH yield source
- Fix batchSwap limits on generalisedExit
=> Release 0.1.40

balancer-js/examples/pools/emissions.ts, balancer-js/src/modules/data/types.ts, balancer-js/src/modules/pools/emissions/index.spec.ts, balancer-js/src/modules/pools/emissions/index.ts, balancer-js/src/modules/pools/index.ts, balancer-js/src/test/factories/index.ts, balancer-js/src/test/factories/liquidity-gauges.ts
Adding small service to query BAL emissions per pool.
=> new: emissions service

balancer-js/package.json, balancer-js/rollup.config.ts, balancer-js/yarn.lock
See [Asana task](https://app.asana.com/0/1201380039585484/1203663360440649/f)
This appears to have no adverse effects:
- Package size doesn't seem to increase
- Front end runs with no issues
=> Move peer dependencies into dependencies to improve dev UX.

balancer-js/README.md, balancer-js/examples/helpers/index.ts, balancer-js/examples/helpers/print-logs.ts, balancer-js/examples/helpers/shorten-address.ts, balancer-js/examples/joinGeneralisedComposableStable.ts
Another join example as part of tutorial work. Simplified for a forked mainnet.
=> Another join example

balancer-js/examples/data/token-yields.ts, balancer-js/src/modules/data/token-yields/repository.ts, balancer-js/src/modules/data/token-yields/tokens/tranchess.spec.ts, balancer-js/src/modules/data/token-yields/tokens/tranchess.ts
Adding APR source for qETH token from Tranchess.
=> ✨ Tranchess APRs

balancer-js/examples/pools/liquidity.gnosis.ts, balancer-js/src/lib/utils/debouncer.ts, balancer-js/src/modules/data/token-prices/coingecko.ts, balancer-js/src/modules/data/token-prices/provider.ts
adding support for gnosis chain in coingecko API
=> 👷Coingecko gnosis config

balancer-js/examples/data/token-yields.ts, balancer-js/src/modules/data/token-yields/repository.ts, balancer-js/src/modules/data/token-yields/tokens/tranchess.ts, balancer-js/src/modules/data/token-yields/tokens/usdr.spec.ts, balancer-js/src/modules/data/token-yields/tokens/usdr.ts
Changing the address to lowercase when calling the function "fetch";
=> Adding USDR APR on the token yields;

balancer-js/src/modules/pools/index.ts, balancer-js/src/modules/pools/pools.spec.ts, balancer-js/src/modules/pools/proportional-amounts/index.ts, balancer-js/src/modules/pools/proportional-amounts/proportional-amounts.spec.ts
Adding a function to calculate proportional amounts relative to a chosen token. Useful for minimising price impacts when joining with more liquidity.
=> New feature: proportional amounts helper

balancer-js/src/modules/exits/exits.module.ts, balancer-js/src/modules/joins/joins.module.ts
Hiding methods used privately from the external interface.
=> 🧹setting private scopes

balancer-js/src/modules/graph/graph.ts, balancer-js/src/modules/pools/pool-type-concerns.ts, balancer-js/src/modules/pools/queries/get_encoder.ts, balancer-js/src/types.ts
Assuming they can use the same concerns as AaveLinear
=> Adding EulerLinear

balancer-js/src/modules/subgraph/balancer-v2/Pools.graphql, balancer-js/src/modules/subgraph/generated/balancer-subgraph-types.ts
Apply same fix as #333 to TokenTree tokens
=> Fix TokenTree tokens order

balancer-js/src/modules/pools/pool-types/concerns/composableStable/exit.concern.ts
Adding unwrapping of native asset for exit with exact tokens out
=> Composable Stable Exit Concern - Unwrap WETH on Exit with Exact Tokens Out

balancer-js/src/modules/pools/pool-types/concerns/stable/exit.concern.ts
Unwrapping wETH when necessary on exactTokensOut;
=> Stable Pool Exit Concern - Unwrapping wETH on Exit with Exact Tokens Out;

.github/workflows/balancer-js.yaml, balancer-js/hardhat.config.polygon.ts
- Future tests in #335 need Polygon node. This adds config for CI.
=> Polygon ci

balancer-js/src/lib/utils/index.ts, balancer-js/src/lib/utils/poolHelper.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/exit.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/exit.concern.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/exitV1.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/join.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/join.concern.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/join.concern.ts, balancer-js/src/test/lib/utils.ts
- Refactoring Exit concern functions;
- Refactoring Exit concern integration tests;
- Adding unit tests file;
=> Weighted Pool Join/Exit Concern - Refactoring function and tests;

balancer-js/src/modules/data/pool/subgraph.ts, balancer-js/src/modules/pools/apr/apr.ts
=> fix: Default protocol fees are 50%

balancer-js/src/modules/contracts/contracts.module.ts, balancer-js/src/modules/contracts/implementations/base-pool.ts
Simple base pool contract factory to interact with pools.
=> ✨ base pool contract factory

balancer-js/src/modules/contracts/contracts.module.spec.ts, balancer-js/src/modules/pools/apr/apr.integration.spec.ts, balancer-js/src/modules/sdk.module.ts
Provider gets instantiated in the Sor as JsonRpcProvider. It's useful to have that type when working with the same provider externally.
=> 🧹use JsonRpcProvider type

balancer-js/src/modules/data/index.ts, balancer-js/src/modules/data/pool/subgraphOnChain.ts
See Asana [ticket](https://app.asana.com/0/1201380039585484/1203761780189071/f)
=> Pass subgraphRepo as dependency to subgraphOnChain

balancer-js/src/modules/pools/pool-types/concerns/composableStable/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exitV1.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/exitV2.concern.integration.spec.ts
We were incorrectly handling single token index which was highlighted when using a token with index > BPT index.
=> Fix single token index

balancer-js/examples/data/pool-subgraph.ts, balancer-js/src/modules/data/pool/subgraph.ts, balancer-js/src/types.ts
=> fix: pool subgraph type

balancer-js/README.md, balancer-js/src/lib/utils/index.ts, balancer-js/src/lib/utils/poolHelper.ts, balancer-js/src/lib/utils/slippageHelper.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/join.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/join.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/linear/exit.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/linear/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/linear/join.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/metaStable/join.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/join.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/join.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/stablePhantom/join.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/types.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/join.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/weighted/join.concern.ts, balancer-js/src/test/lib/joinHelper.ts, balancer-js/src/test/lib/utils.ts, balancer-js/src/types.ts
- Add priceImpact as output on join concerns
- Add priceImpact check to join integration tests
- Refactor join concern integration tests to reuse code, improve readability and increase test performance
=> Price impact join concerns

balancer-js/examples/pools/weighted/create-and-init-join.ts, balancer-js/src/lib/abi/WeightedPool.json, balancer-js/src/lib/abi/WeightedPoolFactory.json, balancer-js/src/lib/constants/config.ts, balancer-js/src/lib/utils/index.ts, balancer-js/src/modules/pools/factory/types.ts, balancer-js/src/modules/pools/factory/weighted/weighted.factory.integration.spec.ts, balancer-js/src/modules/pools/factory/weighted/weighted.factory.spec.ts, balancer-js/src/modules/pools/factory/weighted/weighted.factory.ts
Updating:
- Pool Factory Addresses;
- Updating parameters;
- Updating tests and example;
=> Weighted Pool Creation - Updating to V4

balancer-js/src/modules/data/token-yields/repository.ts, balancer-js/src/modules/pools/apr/apr.ts, balancer-js/src/modules/zaps/bbausd2-migrations/bbausd1.integration.spec.ts, balancer-js/src/modules/zaps/bbausd2-migrations/stabal3.integration.spec.ts, balancer-js/src/modules/zaps/bbausd2-migrations/stables.integration.spec.ts
Fixing an issue where repository was prematurely returning 0
=> fix: token yields repository

balancer-js/examples/pools/helper.ts, balancer-js/src/lib/utils/index.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/join.concern.integration.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/composableStable/join.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/stable/join.concern.ts, balancer-js/src/test/lib/joinHelper.ts, balancer-js/src/test/lib/utils.ts
Bugfixing insert function to accept inserting in the last position (push) Adding error throw to replace function;
Accepting undefined value for slots on setUpExample function;
=> Bugfixing Composable Stable and Stable to accept join with native asset;

balancer-js/src/modules/pools/pool-types/concerns/linear/exit.concern.spec.ts, balancer-js/src/modules/pools/pool-types/concerns/linear/exit.concern.ts
- This change applies to LinearPools only
=> Remove BPT amount from buildRecoveryExit output

balancer-js/src/lib/constants/config.ts, balancer-js/src/lib/constants/network.ts
Addresses taken from https://github.com/balancer/balancer-v2-monorepo/pull/2474 
Tokens from https://zkevm.polygonscan.com/tokens
=> Feat: zkEVM support

balancer-js/src/modules/exits/exits.module.ts
See [this](https://app.asana.com/0/1201380039585484/1204581966955664/f) Asana task for more info
=> Fix toInternalBalance on createExitPoolProportional

balancer-js/src/lib/abi/Multicall.json, balancer-js/src/lib/utils/multiCaller.ts, balancer-js/src/modules/claims/ClaimService.spec.ts, balancer-js/src/modules/claims/ClaimService.ts, balancer-js/src/modules/contracts/contracts.module.ts, balancer-js/src/modules/contracts/implementations/multicall.ts, balancer-js/src/modules/contracts/implementations/veBAL.ts, balancer-js/src/modules/data/fee-distributor/repository.spec.ts, balancer-js/src/modules/data/fee-distributor/repository.ts, balancer-js/src/modules/data/gauge-controller/multicall.spec.ts, balancer-js/src/modules/data/gauge-controller/multicall.ts, balancer-js/src/modules/data/index.ts, balancer-js/src/modules/data/liquidity-gauges/multicall.spec.ts, balancer-js/src/modules/data/liquidity-gauges/multicall.ts, balancer-js/src/modules/data/liquidity-gauges/provider.ts, balancer-js/src/modules/data/protocol-fees/provider.ts, balancer-js/src/modules/data/token-prices/aave-rates.ts, balancer-js/src/modules/data/token-prices/provider.ts, balancer-js/src/modules/pools/apr/apr.ts, balancer-js/src/modules/sdk.module.ts, balancer-js/src/modules/sor/pool-data/onChainData.ts
New gauges store information about BAL issued / second as `inflation_rate`. We will use that to calculate weekly rewards distributed by a gauge.
=> Cross-chain gauges support

balancer-js/src/lib/abi/AaveLinearPoolFactory.json, balancer-js/src/lib/abi/ERC4626LinearPoolFactory.json, balancer-js/src/lib/abi/GearboxLinearPoolFactory.json, balancer-js/src/lib/abi/YearnLinearPoolFactory.json, balancer-js/src/lib/constants/config.ts, balancer-js/src/lib/utils/index.ts, balancer-js/src/modules/pools/factory/linear/linear.factory.integration.spec.ts, balancer-js/src/modules/pools/factory/linear/linear.factory.ts, balancer-js/src/modules/pools/factory/pool-factory.ts, balancer-js/src/modules/pools/factory/types.ts
Adding salt  creation parameter to all linear pool types except EulerLinearPool;
=> Updating Linear Pool to V4/V2

balancer-js/src/modules/pools/queries/params_builder.ts, balancer-js/src/modules/pools/queries/queries.integration.spec.ts
User data should not have a value for BPT but main function should.
=> fix-query-params-builder

balancer-js/examples/joinGeneralised.ts, balancer-js/src/balancerErrors.ts, balancer-js/src/modules/joins/joins.module.ts
* Add early error checks for inputs.
* Refactor example to make it easier to run with different networks/pools/tokens.
=> Improve generalisedJoin input checking and example

balancer-js/src/lib/constants/config.ts
Just a simple fix on the Optimism platformId
=> Fixing platformId for Optimism network

balancer-js/src/lib/constants/config.ts, balancer-js/src/types.ts
Didn't find token address for Rinkeby, Ropsten and Kovan networks;
=> Turning BAL Token address required for all networks;

balancer-js/src/lib/utils/index.ts, balancer-js/src/modules/data/pool/fallback.ts, balancer-js/src/modules/data/token-prices/provider.ts, balancer-js/src/modules/data/token-yields/repository.ts, balancer-js/src/modules/pools/apr/apr.ts, balancer-js/src/modules/pools/impermanentLoss/impermanentLossService.ts, balancer-js/src/modules/pools/index.ts, balancer-js/src/modules/sor/pool-data/onChainData.ts, balancer-js/src/modules/vaultModel/poolSource.ts
Changing some Balancer error logs to warnings
=> Changing some error logs to warnings;

balancer-js/src/lib/utils/index.ts, balancer-js/src/lib/utils/logger.ts, balancer-js/src/modules/data/pool/fallback.ts, balancer-js/src/modules/data/token-prices/provider.ts, balancer-js/src/modules/data/token-yields/repository.ts, balancer-js/src/modules/exits/exits.module.ts, balancer-js/src/modules/joins/joins.module.ts, balancer-js/src/modules/pools/apr/apr.ts, balancer-js/src/modules/pools/impermanentLoss/impermanentLossService.ts, balancer-js/src/modules/pools/index.ts, balancer-js/src/modules/pools/pool-types/concerns/fx/exit.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/fx/join.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/fx/spotPrice.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/gyro/join.concern.ts, balancer-js/src/modules/pools/pool-types/concerns/gyro/spotPrice.concern.ts, balancer-js/src/modules/sdk.module.ts, balancer-js/src/modules/sor/pool-data/onChainData.ts, balancer-js/src/modules/swaps/joinExit/actions/exit.ts, balancer-js/src/modules/swaps/joinExit/actions/swap.ts, balancer-js/src/modules/swaps/joinExit/joinAndExit.ts, balancer-js/src/modules/vaultModel/poolModel/join.ts, balancer-js/src/modules/vaultModel/poolSource.ts, balancer-js/src/types.ts
* Aura and Gareth reported some unnecessary output errors, See [Asana ticket](https://app.asana.com/0/1201380039585484/1204962208766237/f)
* Added Logger Singleton to avoid having to pass as arguments to various classes (ChatGPT suggestion)
* Optional `enableLogging` config var added to `BalancerSdkConfig`. If set to true will output messages via Logger.
* Replaced console.log/warn as neccessary
* Removed some unused params to fix linting
=> Add logger to suppress production logs

balancer-js/src/lib/constants/config.ts
An user was having problems with getSpotPrice method, and this was the cause
=> adding poolDataQueries address for goerli chain;

balancer-js/src/lib/constants/config.ts
=> Revert to layer0 BAL.

balancer-js/examples/pools/aprs/aprs.zkevm.ts, balancer-js/src/modules/data/liquidity-gauges/provider.ts
BAL emissions APR is not working on zkEVM gauges because that factory is filtered out. I also updated the RPC used in the example since the old one was falling to make the multicall.
=> fix zkevm gauges inflation rate

balancer-js/src/lib/constants/config.ts
Per Tritium's request:
- rETH and ETHx as hop tokens
- rETH/wETH as mid pool
=> Add hop tokens and mid pool
